pub struct Entry {
    pub name: &'static str,
    pub syntax: &'static str,
    pub summary: &'static str,
    pub details: &'static str,
    pub examples: &'static [&'static str],
    pub backend: &'static str,
}
pub const COMMANDS: &[Entry] = &[
    Entry {
        name: "help",
        syntax: "[command]",
        summary: "Краткая справка",
        details: "Показывает краткое назначение команды, синтаксис, примеры и доступные параметры. Для подробного объяснения используйте mono manual <command>.",
        examples: &["mono help", "mono help delete"],
        backend: "Показывает синтаксис одной команды или весь список.",
    },
    Entry {
        name: "manual",
        syntax: "[command] OR backend <command>",
        summary: "Подробное руководство",
        details: "Руководство по возможностям Mono: поведение, ограничения и примеры. Техническое описание реализации доступно отдельно: mono manual backend <command>. Неизвестная команда не перенаправляется в системную документацию.",
        examples: &[
            "mono manual",
            "mono manual network",
            "mono manual backend delete",
        ],
        backend: "Built-in Mono catalog; no system man fallback. Technical view: mono manual backend <command>.",
    },
    Entry {
        name: "version",
        syntax: "",
        summary: "Версия Mono/Monux",
        details: "Показывает версию установленного Mono/Monux.",
        examples: &["mono version"],
        backend: "Версия установленного исполняемого файла.",
    },
    Entry {
        name: "status",
        syntax: "[network/service]",
        summary: "Состояние системы или службы",
        details: "Без аргумента показывает состояние системы. network показывает сетевые интерфейсы. Имя службы показывает её состояние; неактивная служба может вернуть код ошибки.",
        examples: &["mono status", "mono status network", "mono status sshd"],
        backend: "Без аргумента: система. network: интерфейсы. Имя службы: systemctl status. Неактивная служба может вернуть ненулевой код.",
    },
    Entry {
        name: "info",
        syntax: "<package/path/device>",
        summary: "Информация об объекте",
        details: "Показывает сведения о файле, диске или пакете программы. Для файлов укажите путь, например ./notes.txt. Информация о пакете берётся из доступного каталога программ.",
        examples: &[
            "mono info firefox",
            "mono info /dev/sda",
            "mono info ./notes.txt",
        ],
        backend: "Файл: stat. Блочное устройство: lsblk. Пакет: pacman -Si по локальной базе репозиториев. Для отсутствующего файла используйте ./имя.",
    },
    Entry {
        name: "list",
        syntax: "<apps/disks/services>",
        summary: "Список объектов",
        details: "Показывает объекты выбранного типа: apps — все установленные пакеты, включая библиотеки; disks — диски и разделы; services — зарегистрированные службы.",
        examples: &["mono list apps", "mono list disks", "mono list services"],
        backend: "apps показывает все установленные пакеты, включая библиотеки; disks — блочные устройства; services — unit-файлы служб.",
    },
    Entry {
        name: "create",
        syntax: "<file/dir/user> <name>",
        summary: "Создать объект",
        details: "Создаёт пустой файл, каталог или пользователя. Существующий файл не перезаписывается. Родительский каталог должен существовать. Новый пользователь получает домашний каталог; вход по паролю заблокирован до отдельной настройки пароля. Создание пользователя требует подтверждения и прав администратора.",
        examples: &[
            "mono create file notes.txt",
            "mono create dir projects",
            "mono create user alex",
        ],
        backend: "Файл создаётся пустым без перезаписи, каталог без автоматического создания родителей. Пользователь получает домашний каталог и заблокированный пароль; задайте пароль через passwd.",
    },
    Entry {
        name: "delete",
        syntax: "<target> [options]",
        summary: "Удалить объект",
        details: "Удаляет файлы, каталоги и учётные записи пользователей.\n\nПо умолчанию файлы и каталоги отправляются в корзину, если окружение её поддерживает.\nЕсли корзина недоступна, Mono сообщает об ошибке и не удаляет объект окончательно.\n\n--permanent\n    Удаляет объект без помещения в корзину. Восстановление через корзину невозможно.\n\n--force\n    Разрешает удаление непустого каталога. Не отменяет подтверждение,\n    права доступа и защиту критических путей.\n\n--dry-run\n    Ничего не изменяет. Показывает объект, способ удаления и уровень риска.\n\nУровни риска:\n    🟢 обычный пользовательский файл или каталог\n    🟡 системный путь: требуется особая осторожность\n    🔴 критические каталоги системы: удаление запрещено\n\nMono запрашивает подтверждение yes перед удалением. Символическая ссылка удаляется\nкак ссылка, её целевой объект сохраняется. Каталог с данными требует --force.\n--permanent и --force можно сочетать. Неизвестные параметры вызывают ошибку.\n\nУчётная запись: mono delete user alex. Домашний каталог сохраняется.\nСистемные пользователи защищены; --force и --permanent для учётных записей не применяются.\nДля имени, начинающегося с --, используйте mono delete -- <имя> или путь ./<имя>.",
        examples: &[
            "mono delete test.txt",
            "mono delete ./build --force",
            "mono delete test.txt --permanent",
            "mono delete ./build --force --permanent --dry-run",
        ],
        backend: "file/directory to trash → gio trash -- <path>\npermanent file → rm -- <path>\npermanent empty directory → rmdir -- <path>\npermanent nonempty directory (--force) → rm -r --one-file-system -- <path>\nuser account → userdel -- <user>\nNo fallback from trash to permanent deletion. Protected paths are checked before execution.",
    },
    Entry {
        name: "copy",
        syntax: "<source> <destination>",
        summary: "Скопировать файл или каталог",
        details: "Копирует файл или каталог, сохраняя атрибуты и ссылки. Каталоги копируются вместе с содержимым. При совпадении имён запрашивается подтверждение перезаписи.",
        examples: &[
            "mono copy notes.txt backup/",
            "mono copy ./project ~/backup/",
        ],
        backend: "cp -a сохраняет атрибуты и симлинки; каталог копируется рекурсивно. При совпадении имён cp спрашивает о перезаписи.",
    },
    Entry {
        name: "move",
        syntax: "<source> <destination>",
        summary: "Переместить или переименовать",
        details: "Перемещает или переименовывает объект. При совпадении имён запрашивается подтверждение перезаписи.",
        examples: &[
            "mono move old.txt new.txt",
            "mono move file.txt ~/Documents/",
        ],
        backend: "mv с интерактивным подтверждением перезаписи.",
    },
    Entry {
        name: "find",
        syntax: "<pattern> [directory]",
        summary: "Найти файлы и каталоги",
        details: "Ищет файлы и каталоги по имени от текущего или указанного каталога. Маску заключайте в кавычки. Поиск не переходит по символическим ссылкам.",
        examples: &["mono find report.pdf", "mono find \"*.log\" /var/log"],
        backend: "Поиск по имени через find от текущего каталога или указанного корня. Маску заключайте в кавычки: mono find \"*.log\" /var/log. Симлинки не обходятся.",
    },
    Entry {
        name: "read",
        syntax: "<file>",
        summary: "Прочитать файл",
        details: "Показывает содержимое файла в терминале. Большой файл выводится целиком.",
        examples: &["mono read config.toml"],
        backend: "Выводит содержимое через cat; для больших файлов используйте внешний pager.",
    },
    Entry {
        name: "edit",
        syntax: "<file>",
        summary: "Редактировать файл",
        details: "Открывает файл в настроенном редакторе. По умолчанию используется micro. Настройка VISUAL имеет приоритет над EDITOR; задавайте один исполняемый файл без дополнительных аргументов.",
        examples: &["mono edit config.toml"],
        backend: "VISUAL, затем EDITOR, иначе micro. Переменная задаёт один исполняемый файл без аргументов; shell не используется.",
    },
    Entry {
        name: "open",
        syntax: "<path/app/URL>",
        summary: "Открыть объект",
        details: "Открывает файл, каталог или адрес в подходящем приложении графической сессии. Имя приложения запускает его напрямую. Запуск процесса ещё не подтверждает готовность окна. В окружении без графики действие может быть недоступно.",
        examples: &[
            "mono open ~/Documents",
            "mono open firefox",
            "mono open https://example.com",
        ],
        backend: "Путь/URL открывает xdg-open в графической сессии. Приложение — исполняемый файл /usr/bin. В WSL без графической среды GUI может быть недоступен.",
    },
    Entry {
        name: "permissions",
        syntax: "<path> [executable/octal]",
        summary: "Права доступа",
        details: "Показывает права доступа или меняет их для одного объекта. executable разрешает владельцу запускать файл. Также принимается числовой режим из 3–4 восьмеричных цифр. Изменение требует подтверждения, не применяется рекурсивно.",
        examples: &[
            "mono permissions script.sh",
            "mono permissions script.sh executable",
        ],
        backend: "Без режима показывает права; executable добавляет u+x, числовой режим принимает 3/4 восьмеричные цифры. Изменение требует yes и не рекурсивно.",
    },
    Entry {
        name: "owner",
        syntax: "<path> [user]",
        summary: "Владелец файла",
        details: "Показывает владельца и группу либо меняет владельца одного объекта. Изменение требует подтверждения и соответствующих прав.",
        examples: &["mono owner file.txt", "mono owner file.txt alex"],
        backend: "Просмотр пользователя и группы либо смена пользователя через chown. Не рекурсивно; изменение требует yes и соответствующих прав.",
    },
    Entry {
        name: "search",
        syntax: "<query>",
        summary: "Поиск пакетов",
        details: "Ищет программы и пакеты в доступном каталоге. Фразу заключайте в кавычки. Поиск использует локальные сведения репозиториев и поддерживает регулярные выражения.",
        examples: &["mono search firefox", "mono search \"video editor\""],
        backend: "pacman -Ss ищет в локальных базах репозиториев, запрос может быть регулярным выражением. Фразу заключайте в кавычки.",
    },
    Entry {
        name: "install",
        syntax: "<package>",
        summary: "Установить пакет",
        details: "Устанавливает пакет и необходимые зависимости. Уже установленный актуальный пакет пропускается. Изменения подтверждаются перед установкой; требуются права администратора.",
        examples: &["mono install firefox", "mono install git"],
        backend: "pacman -S --needed, с интерактивным подтверждением pacman. Требуются root и настроенные репозитории.",
    },
    Entry {
        name: "uninstall",
        syntax: "<package>",
        summary: "Удалить пакет",
        details: "Удаляет установленный пакет после подтверждения. Автоматическое удаление ненужных зависимостей не выполняется.",
        examples: &["mono uninstall firefox"],
        backend: "pacman -R, с подтверждением pacman; автоматическое рекурсивное удаление зависимостей не выполняется.",
    },
    Entry {
        name: "update",
        syntax: "[package]",
        summary: "Обновить систему",
        details: "Обновляет систему целиком. Если указана программа, она включается в ту же операцию. В Arch отдельное частичное обновление программы и обновление только источников не выполняются. Требуются права администратора и подтверждение.",
        examples: &["mono update", "mono update firefox"],
        backend: "Всегда полное pacman -Syu. Указанный пакет дополнительно передаётся в ту же транзакцию. Обновление только баз или частичное обновление системы не выполняется.",
    },
    Entry {
        name: "clean",
        syntax: "[packages]",
        summary: "Очистить кэш пакетов",
        details: "Очищает кэш пакетов после подтверждения. Пользовательские файлы не затрагиваются; автоматического поиска ненужных зависимостей нет.",
        examples: &["mono clean", "mono clean packages"],
        backend: "Интерактивный pacman -Sc; не удаляет пользовательские файлы и не ищет автоматически ненужные зависимости.",
    },
    Entry {
        name: "start",
        syntax: "<service/app>",
        summary: "Запустить службу или приложение",
        details: "Запускает службу или приложение. При совпадении имени приоритет имеет существующая служба; её можно указать полностью, например nginx.service.",
        examples: &["mono start nginx", "mono start firefox"],
        backend: "Сначала ищет загруженный unit systemd; иначе запускает /usr/bin/<app>. При конфликте используйте полное имя службы .service.",
    },
    Entry {
        name: "stop",
        syntax: "<service/process>",
        summary: "Штатно остановить объект",
        details: "Штатно останавливает службу или посылает процессам запрос на завершение. Для имени приложения выбираются все доступные процессы с точным именем до 15 байт. Требуется подтверждение.",
        examples: &["mono stop nginx", "mono stop firefox"],
        backend: "Служба: systemctl stop. Процесс: SIGTERM всем процессам с точным именем comm (до 15 байт) в пределах прав пользователя. Требует yes.",
    },
    Entry {
        name: "restart",
        syntax: "<service>",
        summary: "Перезапустить службу",
        details: "Перезапускает службу после подтверждения. Перезапуск произвольного приложения пока не поддерживается.",
        examples: &["mono restart NetworkManager", "mono restart bluetooth"],
        backend: "systemctl restart для существующей службы. Требует yes. Перезапуск произвольных GUI-приложений пока не поддерживается.",
    },
    Entry {
        name: "kill",
        syntax: "<name/PID>",
        summary: "Принудительно завершить",
        details: "Принудительно завершает процесс по номеру или все доступные процессы с точным именем до 15 байт. Несохранённые данные могут быть потеряны. Требуется подтверждение; процессы 0, 1 и сам Mono защищены.",
        examples: &["mono kill firefox", "mono kill 4821"],
        backend: "SIGKILL: PID или все процессы с точным именем comm до 15 байт. Запрещены PID 0, 1 и собственный PID. Требует yes.",
    },
    Entry {
        name: "enable",
        syntax: "<service>",
        summary: "Включить автозапуск службы",
        details: "Включает автоматический запуск службы. Служба не запускается немедленно; для этого используйте mono start. Требуется подтверждение.",
        examples: &["mono enable sshd", "mono enable bluetooth"],
        backend: "systemctl enable; службу немедленно не запускает. Требует yes.",
    },
    Entry {
        name: "disable",
        syntax: "<service>",
        summary: "Отключить автозапуск службы",
        details: "Отключает автоматический запуск службы. Уже работающая служба не останавливается; используйте mono stop. Требуется подтверждение.",
        examples: &["mono disable sshd", "mono disable bluetooth"],
        backend: "systemctl disable; работающую службу не останавливает. Требует yes.",
    },
    Entry {
        name: "usage",
        syntax: "[process/path]",
        summary: "Использование ресурсов",
        details: "Показывает использование памяти и процессора. Имя программы ограничивает список её процессами; путь показывает занятость файловой системы, а не размер каталога. CPU — среднее за время жизни процесса; RSS указан в КиБ.",
        examples: &["mono usage", "mono usage firefox", "mono usage /"],
        backend: "Общее: free и ps. Процесс: CPU, RAM, RSS (КиБ); CPU — среднее за время жизни. Путь: занятость файловой системы через df, не размер каталога.",
    },
    Entry {
        name: "check",
        syntax: "network OR disk <device>",
        summary: "Проверка объекта",
        details: "network проверяет локальные адреса и выбор маршрута без отправки пакетов. Для проверки подключения используйте mono network check <host>. disk читает показатели здоровья устройства, если оно их поддерживает; не проверяет файловую систему и не ремонтирует диск.",
        examples: &["mono check network", "mono check disk /dev/sda"],
        backend: "network показывает интерфейсы без внешнего запроса; для соединения используйте network check <host>. disk запускает read-only smartctl -H: SMART, не fsck и не ремонт. Нужен smartmontools; виртуальные диски могут не поддерживаться.",
    },
    Entry {
        name: "logs",
        syntax: "[boot/service]",
        summary: "Системные журналы",
        details: "Показывает последние 100 записей системного журнала. boot ограничивает текущей загрузкой; имя службы — её записями. Доступ зависит от прав пользователя.",
        examples: &["mono logs", "mono logs boot", "mono logs NetworkManager"],
        backend: "Последние 100 записей journalctl, без pager; boot ограничивает текущей загрузкой. Доступ зависит от прав пользователя.",
    },
    Entry {
        name: "connect",
        syntax: "wifi <SSID> OR bluetooth <name/MAC>",
        summary: "Подключиться",
        details: "Подключает Wi-Fi по имени сети или ранее спаренное Bluetooth-устройство по уникальному имени/адресу. Пароль Wi-Fi запрашивается интерактивно. Требуется подтверждение. Нужны доступные адаптеры и поддержка соединений в окружении.",
        examples: &[
            "mono connect wifi Home",
            "mono connect bluetooth headphones",
        ],
        backend: "Wi-Fi: NetworkManager/nmcli --ask запрашивает пароль, включает Wi-Fi. Bluetooth: bluetoothctl, устройство должно быть спарено. Имя должно быть уникальным. Требует yes.",
    },
    Entry {
        name: "disconnect",
        syntax: "wifi OR bluetooth <name/MAC>",
        summary: "Отключить соединение",
        details: "wifi выключает Wi-Fi на всех адаптерах. Для повторного включения используйте mono connect wifi <имя>. Bluetooth отключает выбранное устройство. Требуется подтверждение.",
        examples: &[
            "mono disconnect wifi",
            "mono disconnect bluetooth headphones",
        ],
        backend: "wifi выключает все Wi-Fi адаптеры через nmcli radio wifi off. Bluetooth отключает указанное устройство. Требует yes.",
    },
    Entry {
        name: "scan",
        syntax: "<wifi/bluetooth>",
        summary: "Найти сети/устройства",
        details: "Ищет доступные сети Wi-Fi или устройства Bluetooth. Поиск Bluetooth длится до 10 секунд. В виртуальной системе физические адаптеры могут быть недоступны.",
        examples: &["mono scan wifi", "mono scan bluetooth"],
        backend: "Wi-Fi: nmcli с повторным сканированием. Bluetooth: bluetoothctl scan on с таймаутом 10 секунд. В WSL физические адаптеры обычно не представлены как устройства Linux.",
    },
    Entry {
        name: "ping",
        syntax: "<host/IP>",
        summary: "Проверка ICMP",
        details: "Отправляет четыре проверочных ICMP-запроса. Ожидание каждого ответа ограничено двумя секундами. Отсутствие ответа не доказывает отсутствие интернета: адресат может блокировать такие запросы.",
        examples: &["mono ping 1.1.1.1", "mono ping archlinux.org"],
        backend: "Четыре ICMP-запроса с ожиданием ответа до 2 секунд; отсутствие ответа не доказывает отсутствие интернета.",
    },
    Entry {
        name: "network",
        syntax: "[status/interfaces/check <host> [port]]",
        summary: "Сеть и диагностика",
        details: "Показывает адреса и маршруты; interfaces — только интерфейсы. check проверяет разрешение имени до 3 секунд, затем TCP-подключение с общим бюджетом 5 секунд. Порт по умолчанию 443. Для IP проверка имени пропускается. Успех даёт код 0, ошибка — 1. TLS и HTTP не проверяются.",
        examples: &[
            "mono network",
            "mono network interfaces",
            "mono network check archlinux.org",
            "mono network check 127.0.0.1 8080",
        ],
        backend: "Без аргумента/status: адреса и маршруты. interfaces: адреса. check: DNS до 3 секунд, TCP бюджет 5 секунд, порт 443 по умолчанию. Это не TLS/HTTP. DNS-поток завершается при выходе CLI.",
    },
    Entry {
        name: "ip",
        syntax: "[interface [add/delete IP/prefix]]",
        summary: "IP-адреса",
        details: "Показывает адреса всех или одного интерфейса. add/delete временно добавляет или удаляет адрес с длиной префикса. Изменение требует подтверждения и прав администратора; после перезагрузки не сохраняется.",
        examples: &["mono ip", "mono ip eth0", "mono ip eth0 add 192.0.2.2/24"],
        backend: "Просмотр всех/одного интерфейса. add/delete меняет адрес временно до перезагрузки, с подтверждением. Требуются права администратора.",
    },
    Entry {
        name: "dns",
        syntax: "[interface server-IP]",
        summary: "DNS",
        details: "Показывает текущую конфигурацию DNS. Интерфейс и IP сервера задают временную настройку DNS для соединения. Нужна поддержка управления DNS в окружении; изменение требует подтверждения и не сохраняется после перезагрузки.",
        examples: &["mono dns", "mono dns eth0 1.1.1.1"],
        backend: "Без аргументов /etc/resolv.conf. Изменение через resolvectl dns временно, требует systemd-resolved и подтверждения; persistent-настройка пока не реализована.",
    },
    Entry {
        name: "ports",
        syntax: "[port]",
        summary: "Слушающие порты",
        details: "Показывает слушающие TCP/UDP-порты, при указании номера — только выбранный порт. Сведения о владельцах соединений зависят от прав.",
        examples: &["mono ports", "mono ports 22"],
        backend: "ss -lntup, фильтр по локальному порту. Показывает только слушающие TCP/UDP; сведения о процессах зависят от прав.",
    },
    Entry {
        name: "disks",
        syntax: "",
        summary: "Диски и разделы",
        details: "Показывает диски, разделы, размеры, файловые системы, метки и точки подключения. Ничего не изменяет.",
        examples: &["mono disks"],
        backend: "lsblk: тип, размер, файловая система, метка, точки монтирования.",
    },
    Entry {
        name: "mount",
        syntax: "<device>",
        summary: "Подключить файловую систему",
        details: "Подключает файловую систему указанного устройства. Место подключения выбирает окружение автоматически. Требуется подтверждение и доступ к устройству.",
        examples: &["mono mount /dev/sdb1"],
        backend: "udisksctl mount -b, точку монтирования выбирает UDisks. Требует udisks2 и подтверждения; политика доступа определяется системой.",
    },
    Entry {
        name: "unmount",
        syntax: "<device>",
        summary: "Отключить файловую систему",
        details: "Отключает файловую систему устройства после подтверждения. Принудительное отключение занятой файловой системы не выполняется.",
        examples: &["mono unmount /dev/sdb1"],
        backend: "udisksctl unmount -b, без force. Требует подтверждения.",
    },
    Entry {
        name: "format",
        syntax: "<partition> <ext4/vfat/fat32/exfat>",
        summary: "Форматировать раздел",
        details: "Создаёт файловую систему, уничтожая данные раздела. Поддержаны ext4, vfat/fat32 и exfat. Целые диски и занятые разделы запрещены. Перед действием нужно ввести полный путь раздела. Требуются права администратора. Это не разметка диска и не установка системы.",
        examples: &["mono format /dev/sdb1 ext4"],
        backend: "Уничтожает данные. Только раздел: запрещены целые диски, loop и mapped volumes. Проверяет mountpoints, swap и holders перед подтверждением и перед запуском. Нужно ввести полный путь раздела. Требуются root и mkfs для выбранной ФС. Не заменяет установщик/разметку диска.",
    },
    Entry {
        name: "reboot",
        syntax: "",
        summary: "Перезагрузить",
        details: "Перезагружает систему после подтверждения yes. Сохраните открытые документы. В виртуальном окружении поведение зависит от его возможностей.",
        examples: &["mono reboot"],
        backend: "systemctl reboot, только после yes. В WSL результат зависит от поддержки systemd/WSL.",
    },
    Entry {
        name: "shutdown",
        syntax: "",
        summary: "Выключить",
        details: "Выключает систему после подтверждения yes. Сохраните открытые документы. В WSL команда не вызывает выключение Windows напрямую.",
        examples: &["mono shutdown"],
        backend: "systemctl poweroff, только после yes. Не вызывает выключение Windows напрямую.",
    },
    Entry {
        name: "sleep",
        syntax: "",
        summary: "Сон системы",
        details: "Переводит систему в сон после подтверждения yes, если это поддерживается оборудованием и окружением.",
        examples: &["mono sleep"],
        backend: "systemctl suspend после yes. В WSL и на неподдерживаемом оборудовании может быть недоступен.",
    },
    Entry {
        name: "lock",
        syntax: "",
        summary: "Блокировать сессию",
        details: "Запрашивает блокировку текущей пользовательской сессии. Требуется работающая блокировка экрана в оболочке. Успешная отправка запроса сама по себе не доказывает, что экран заблокирован.",
        examples: &["mono lock"],
        backend: "loginctl lock-session по XDG_SESSION_ID. Нужен установленный и работающий locker оболочки. Успешная отправка запроса не доказывает фактическую блокировку экрана.",
    },
];
